### ISSUE TITLE
Proxy Parameters are Incorrect

### ISSUE THREAD

**Issue by sighphyre** [YellowfinBI/Docker#2]
Setting the PROXY_HOST variable causes the image to set a property in the server.xml file called proxyHost of that value. This is ignored by tomcat and a warning is raised on startup. This property should be proxyName instead. Overriding this correctly respects the proxy configuration

**Comment by JakeRapinett** [comment]
Hey @sighphyre,
We'll be pushing a patch for this within the next day or 2.

**Comment by JakeRapinett** [comment]
Hey @sighphyre 
This has been fixed in the latest commit - https://github.com/YellowfinBI/Docker/commit/f3916b890f136d438f28797a760fa0bd07b8fc01

**Comment by sighphyre** [comment]
Thanks so much for the quick turn around, folks!
